#!/bin/bash

#blocks and threads as given in task
blocks=(60 120 180 240 300 360 420 600)
threads=(16 32 48 64 80 96 112 128 144 160)

#make an output file to contain all the results
echo "NUM_BLOCK,NUM_THREAD,Time(s)" > task3_results.csv

#loop over given setups
for b in "${blocks[@]}"; do
  for t in "${threads[@]}"; do
    echo "Running NUM_BLOCK=$b NUM_THREAD=$t"
    # Run the executable and capture the time
    time_str=$(./cpi_cuda_scaling $b $t | grep "computed in" | awk '{print $6}')
    echo "$b,$t,$time_str" >> timing_results.csv
  done
done
