#!/bin/bash -l
#SBATCH --account=uzh8
#SBATCH --job-name="sum_p_4"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=4
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --output=output_sum_p_4.log
#SBATCH --error=error_sum_p_4.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./sum_p
