#!/bin/bash
#SBATCH --job-name=poisson_omp_1
#SBATCH --output=poisson_omp_1_%j.out
#SBATCH --error=poisson_omp_1_%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:05:00
#SBATCH --mem=1G

export OMP_NUM_THREADS=1

# Run the OpenMP executable
./poisson_solver_omp